uuid = "62e2a3fd-f4df-4b53-abc5-b73d2a36b672"
name = "View script variables"
authors = ["Sophist"]
maintainers = ["MusicBrainz Picard Team"]
description = "Display a dialog box listing the metadata tags and variables for the track / file."
api = ['3.0']
license = "GPL-2.0"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
long_description = """
Display a dialog box listing the metadata tags and variables for the track / file.

This allows you to see metadata variables beginning with "~" which are not normally visible in the metadata
pane of the main Picard window, which can be useful when you are writing tagging or file naming scripts.
"""
homepage = "https://github.com/metabrainz/picard-plugin-view-script-variables"
report_bugs_to = "https://tickets.metabrainz.org/issues/?filter=13410"

[name_i18n]
de = "Skriptvariablen anzeigen"
fr = "Afficher les variables du script"
zh_CN = "查看脚本变量"

[description_i18n]
de = "Zeigt ein Dialogfenster mit den Metadaten-Tags und Variablen für den Titel/die Datei an."
fr = "Afficher une boîte de dialogue répertoriant les balises de métadonnées et les variables associées à la piste / au fichier."
zh_CN = "显示一个对话框，列出音轨 / 文件的元数据标签和变量。"

[long_description_i18n]
de = "Zeigt ein Dialogfenster mit den Metadaten-Tags und Variablen für den Titel/die Datei an.\n\nDadurch können Metadatenvariablen eingesehen werden, die mit „~“ beginnen und normalerweise im Metadatenbereich des Picard-Hauptfensters nicht sichtbar sind. Dies kann beim Schreiben von Skripten zum Taggen oder Benennen von Dateien nützlich sein."

fr = "Affiche une boîte de dialogue répertoriant les balises de métadonnées et les variables associées à la piste ou au fichier.\n\nCela vous permet de visualiser les variables de métadonnées commençant par « ~ », qui ne sont normalement pas visibles dans le volet des métadonnées de la fenêtre principale de Picard, ce qui peut s'avérer utile lorsque vous écrivez des scripts de balisage ou de nommage de fichiers."
zh_CN = "显示一个对话框，列出音轨 / 文件的元数据标签和变量。\n\n这允许您查看以 \"~\" 开头的元数据变量，这些变量通常在主 Picard 窗口的元数据窗格中不可见，这在您编写标记或文件命名脚本时可能很有用。"
